### ISSUE TITLE
SeisNoise v0.5.3 fails to compile on M1 Mac

### ISSUE THREAD

**Issue by haakon-e** [tclements/SeisNoise.jl#100]
due to pinned dependencies in SeisIO. See https://github.com/jpjones76/SeisIO.jl/issues/93 and proposed fix https://github.com/jpjones76/SeisIO.jl/pull/94. Depending on how the SeisIO version is bumped after that fix, compat changes may be needed here too.

In a local instance of `SeisNoise.jl` that depends on `SeisIO.jl` with the proposed fix implemented, compilation of this package is successful.

**Comment by tclements** [comment]
Great, thanks for letting me know! I have not tested SeisNoise on an M1/M2. I'll get in touch with Josh Jones to see if he can merge quickly - should be an easy fix.

**Comment by tclements** [comment]
I think the comment using my forked version of SeisIO I mentioned in #101 should fix for now. We are working on moving to use [SeisBase.jl ](https://github.com/SeismoJulia/SeisBase.jl) in the future.

**Comment by tclements** [comment]
We moved to using SeisBase.jl, can confirm SeisNoise.jl works on macOS.
