### ISSUE TITLE
InexactError

### ISSUE THREAD

**Issue by rkoireng** [tclements/SeisNoise.jl#103]
Hi! ,  

I am trying to slice a single channel into 70 secs windows but RawData() is showing InexactError.  Is this because of some constraint on cc_len and cc_step  values?
![Screenshot (96)](https://user-images.githubusercontent.com/43760841/202871779-c3d291c0-bf17-4d00-951a-f69afac19d3f.png)

**Comment by tclements** [comment]
Hi! `RawData` has a check that `cc_len * S.fs` is an integer value. Which version of SeisNoise do you have installed? You may have an older version installed. You can check your version by typing `]` at the repl and then typing `status`. The other thing issue is that the year in the SeisData (`S.t`) above is `-12381`. Incorrect time could cause problems.
