### ISSUE TITLE
 Can't install the package SeisNoise.jl in the Julia.exe for version 1.8.5

### ISSUE THREAD

**Issue by ouyk6** [tclements/SeisNoise.jl#108]
![图片](https://user-images.githubusercontent.com/120694235/220384152-4c73480c-2582-49c3-b5f9-997749edbc4d.png)

**Comment by tclements** [comment]
Hello - this is an SSL problem related to your operating system. Here is a guide how to fix SSL issues on Windows https://komodor.com/learn/how-to-fix-ssl-certificate-problem-unable-to-get-local-issuer-certificate-git-error/. If that guide is not helpful, I would recommend filing an issue with https://github.com/JuliaLang/Pkg.jl/issues.

**Comment by ouyk6** [comment]
Hello,the webcite you provide is not helpful, i can't handle the SSl problem.
https://komodor.com/learn/how-to-fix-ssl-certificate-problem-unable-to-get-local-issuer-certificate-git-error/
