### ISSUE TITLE
rfftfreq not defined

### ISSUE THREAD

**Issue by dylanmikesell** [tclements/SeisNoise.jl#11]
I recently updated to Julia 1.3.1 after seeing that SeisIO issues have been fixed. I tried to run the SeisNoise example on the github front page of the repository. I am now getting the following error.

WARNING: both FFTW and DSP export "rfftfreq"; uses of it in module SeisNoise must be qualified

Looks like there is a problem in these two packages and we need to modify SeisNoise to choose which we are using: FFTW or DSP. Have you seen this error yet and is there a plan to fix it?

The problem occurs on line 29 of phase_shift.jl

`freq = rfftfreq(length(C.x),C.fs)`

**Comment by tclements** [comment]
I have not updated to Julia 1.3.x yet - I'll update and add a fix shortly

**Comment by tclements** [comment]
This was fixed on the master branch but was not pushed to the Julia General registry. I updated the package number such that the master branch is now on the General registry. Once this pull request https://github.com/JuliaRegistries/General/pull/10013 is merged, you should be able to do `pkg> update SeisNoise` to fix.

**Comment by tclements** [comment]
Just waiting for the Julia general to merge https://github.com/JuliaRegistries/General/pull/10015

**Comment by dylanmikesell** [comment]
Okay. Will check back in once this is merged. I tried updating this
morning, but doesn't look like registry has updated SeisNoise yet. Will try
again tonight. Not sure how quickly that merge happens.

**Comment by tclements** [comment]
You can also add the master version of SeisNoise, which is passing builds. 
```julia 
pkg> rm SeisNoise
pkg> add SeisNoise#master
```

**Comment by dylanmikesell** [comment]
Good to know. Will do that!

Dylan

**Comment by tclements** [comment]
The PR to General finally merged. This should be fixed with `pkg> update SeisNoise`. Future version bumps should automerge now that I have the Julia compat system setup.
