### ISSUE TITLE
If the SeisNoise.jl and SeisIO can batch process cross-correlation function between lots of station Seisdata?

### ISSUE THREAD

**Issue by ouyk6** [tclements/SeisNoise.jl#112]
Dear professor,
     I want to know how to use the package of SeisNoise.jl and SeisIO to batch process cross-correlation function between lots of station Seisdata. I hvae got one hour station data cross-correlation function between two station.My codes are as follow.

(base) [Fangfan@localhost ~]$ cd /home/Fangfan/huanan2022/test
(base) [Fangfan@localhost test]$ julia
julia> using Pkg
julia> Pkg.build()
julia> using SeisNoise,SeisIO,Plots
julia> fs = 40. # sampling frequency in Hz
julia> freqmin,freqmax = 0.1,0.2 # min and max frequencies
julia> cc_step, cc_len = 450., 1800. # corrleation step and length in S
julia> maxlag = 60. # maximum lag time in correlation
julia> S1=read_data("sac","2022.07.28.10.14.50.YD202.BHE.sac")
julia> S2=read_data("sac","2022.07.28.10.12.12.YD204.BHE.sac")
julia> merge!(S1)
julia> merge!(S2)
julia> ungap!(S1)
julia> ungap!(S2)    
julia> process_raw!(S1,fs)
julia> process_raw!(S2,fs)
julia> R = RawData.([S1,S2],cc_len,cc_step)
julia> detrend!.(R)
julia> taper!.(R)
julia> bandpass!.(R,freqmin,freqmax,zerophase=true)
julia> FFT = rfft.(R)
julia> whiten!.(FFT,freqmin,freqmax)
julia> C = correlate(FFT[1],FFT[2],maxlag)
julia> clean_up!(C,freqmin,freqmax)
julia> abs_max!(C)
julia> plot(C)
julia> savefig("2.png")

The attachment is the result of the program running
![2](https://user-images.githubusercontent.com/120694235/225307423-4b117a76-a3d6-4746-a10f-03c3a0d573e4.png)

**Comment by tclements** [comment]
You'll have to write scripts (.jl files) to do exactly what you want. You can take a look at the scripts in this repository for examples: https://github.com/tclements/SeisNoise_paper
