### ISSUE TITLE
RawData.() should give a useful error when cc_len > data length

### ISSUE THREAD

**Issue by dylanmikesell** [tclements/SeisNoise.jl#29]
Below is an example. The data length is 600 seconds, while the cc_len is 1800 seconds. The last line fails.
```
using SeisIO, SeisNoise

fs      = 20. # [Hz] resample frequency
cc_len  = 1800 # [s]
cc_step = 450 # [s]

S1 = get_data("FDSN", "TA.I02A..BHZ", src="IRIS", s=string("2007-04-16"), t=600)
S2 = get_data("FDSN", "TA.I02A..BHZ", src="IRIS", s=string("2007-04-16"), t=600)

process_raw!(S1,fs)
process_raw!(S2,fs)

R = RawData.([S1,S2], cc_len, cc_step)
```
There error is

ArgumentError: invalid index: nothing of type Nothing
to_index(::Nothing) at indices.jl:273
to_index(::Array{Float64,1}, ::Nothing) at indices.jl:250
to_indices at indices.jl:301 [inlined]
to_indices at indices.jl:298 [inlined]
getindex at abstractarray.jl:981 [inlined]
nearest_start_end(::SeisChannel, ::Int64, ::Int64) at slicing.jl:81
RawData(::SeisData, ::Int64, ::Int64) at RawData.jl:77
_broadcast_getindex at broadcast.jl:630 [inlined]
getindex at broadcast.jl:563 [inlined]
copy(::Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int64}},Type{RawData},Tuple{Array{SeisData,1},Int64,Int64}}) at broadcast.jl:853
materialize(::Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,Type{RawData},Tuple{Array{SeisData,1},Int64,Int64}}) at broadcast.jl:819
top-level scope at SeisIO_msr_dump.jl:18

It would be better to check the inputs and tell the user they have screwed up and the requested cc_len is longer than the input data. Therefore, there is nothing to index over in terms of time windows. It took me a little while to figure that error out earlier today. I think an assertion should do it.

`@assert length(S1.x[1]) >= cc_len`

You may need to check for the minimum length input SeisData channels though first.

**Comment by tclements** [comment]
I added a `DomainError` if cc_len > length(S[1].x) / S1[1].fs to the master branch.

**Comment by tclements** [comment]
This is fixed in the newest release. Closing.
