### ISSUE TITLE
MutliStageResponse bug

### ISSUE THREAD

**Issue by dylanmikesell** [tclements/SeisNoise.jl#30]
Here is a minimum working example of a bug related to the input SeisData channel and where or not it has a normal PZResp or a multistage response.
```
using SeisIO, SeisNoise

fs      = 20. # [Hz] resample frequency
cc_len  = 1800 # [s]
cc_step = 450 # [s]

S1 = get_data("FDSN", "TA.I02A..BHZ", src="IRIS", s=string("2007-04-16"), t=6000, msr=true)
S2 = get_data("FDSN", "TA.I02A..BHZ", src="IRIS", s=string("2007-04-16"), t=6000)

process_raw!(S1,fs)
process_raw!(S2,fs)

R = RawData.([S1,S2], cc_len, cc_step)
```
The results error is related to an inability to convert object types. It would be nice if RawData() could handle either.

MethodError: Cannot `convert` an object of type MultiStageResp to an object of type PZResp
Closest candidates are:
  convert(::Type{T}, !Matched::LazyJSON.PropertyDicts.PropertyDict) where T at /Users/dmikesell/.julia/packages/LazyJSON/nTpJx/src/PropertyDicts.jl:61
  convert(::Type{T}, !Matched::LazyJSON.Object) where T at /Users/dmikesell/.julia/packages/LazyJSON/nTpJx/src/AbstractDict.jl:82
  convert(::Type{S}, !Matched::T) where {S, T<:(Union{CategoricalArrays.CategoricalString{R}, CategoricalArrays.CategoricalValue{T,R} where T} where R)} at /Users/dmikesell/.julia/packages/CategoricalArrays/dmrjI/src/value.jl:103
  ...
RawData(::SeisData, ::Int64, ::Int64) at RawData.jl:84
_broadcast_getindex at broadcast.jl:630 [inlined]
getindex at broadcast.jl:563 [inlined]
copy(::Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Tuple{Base.OneTo{Int64}},Type{RawData},Tuple{Array{SeisData,1},Int64,Int64}}) at broadcast.jl:853
materialize(::Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{1},Nothing,Type{RawData},Tuple{Array{SeisData,1},Int64,Int64}}) at broadcast.jl:819
top-level scope at SeisIO_msr_dump.jl:13

**Comment by tclements** [comment]
This should be fixed on the master branch now. I added support for `MultiStageResp` in `RawData`, `FFTData` and `CorrData`. Let me know if you have any problems.

**Comment by tclements** [comment]
This is fixed in the newest release. Closing.
