### ISSUE TITLE
process_raw! error related to sampling frequency

### ISSUE THREAD

**Issue by dylanmikesell** [tclements/SeisNoise.jl#67]
Have you had issues with the sampling frequency and process_raw!()? We noticed a new error recently and it took us a little bit to figure out why, because our code was previously working. I paste an example below which uses the example on the SeisNoise.jl page. I download some data and process using the actual sample frequency. That works fine. Then I download the data again and use a quarter of the that sampling frequency during the processing. Then I get a resize error. Any ideas? Have you seen this before?  fs is supposed to  `Downsamples data to sampling rate `fs`` according to compute_fft.jl. What are we screwing up here?

julia> fs = 40. # sampling frequency in Hz
40.0

julia> S1 = get_data("FDSN","CI.SDD..BHZ",src="SCEDC",s=s,t=t)

SeisData with 1 channels (1 shown)
    ID: CI.SDD..BHZ                        
  NAME: Saddleback                         
   LOC: 33.5526 N, -117.662 E, 120.0 m     
    FS: 40.0                               
  GAIN: 6.2652e8                           
  RESP: a0 5.73035e8, f0 0.03, 2z, 5p      
 UNITS: m/s                                
   SRC: http://service.scedc.caltech.edu/… 
  MISC: 4 entries                          
 NOTES: 4 entries                          
     T: 2019-02-03T00:00:00 (0 gaps)       
     X: -1.992e+03                         
        -1.847e+03                         
            ...                            
        -1.106e+03                         
        (nx = 3456000)                     
     C: 0 open, 0 total

julia> process_raw!(S1,fs)

julia> fs = 10.0
10.0

julia> S1 = get_data("FDSN","CI.SDD..BHZ",src="SCEDC",s=s,t=t)
SeisData with 1 channels (1 shown)
    ID: CI.SDD..BHZ                        
  NAME: Saddleback                         
   LOC: 33.5526 N, -117.662 E, 120.0 m     
    FS: 40.0                               
  GAIN: 6.2652e8                           
  RESP: a0 5.73035e8, f0 0.03, 2z, 5p      
 UNITS: m/s                                
   SRC: http://service.scedc.caltech.edu/… 
  MISC: 4 entries                          
 NOTES: 4 entries                          
     T: 2019-02-03T00:00:00 (0 gaps)       
     X: -1.992e+03                         
        -1.847e+03                         
            ...                            
        -1.106e+03                         
        (nx = 3456000)                     
     C: 0 open, 0 total

julia> process_raw!(S1,fs)
ERROR: cannot resize array with shared data
Stacktrace:
 [1] deleteat!(::Array{Float32,1}, ::UnitRange{Int64}) at ./array.jl:838
 [2] #resample!#157(::Int64, ::Float64, ::typeof(resample!), ::SeisData) at /Users/dmikesell/.julia/packages/SeisIO/mlqvk/src/Processing/resample.jl:125
 [3] #resample! at ./none:0 [inlined]
 [4] #process_raw!#127(::Bool, ::typeof(process_raw!), ::SeisData, ::Float64) at /Users/dmikesell/.julia/packages/SeisNoise/I9Knu/src/compute_fft.jl:30
 [5] process_raw!(::SeisData, ::Float64) at /Users/dmikesell/.julia/packages/SeisNoise/I9Knu/src/compute_fft.jl:21
 [6] top-level scope at none:0

**Comment by dylanmikesell** [comment]
Update on this. I just updated to the latest SeisIO.jl and this error appears to be gone now. Will continue to run some tests today and figure out if this really is still an issue or not.

**Comment by dylanmikesell** [comment]
Issue is gone after updating packages. Sorry.

**Comment by tclements** [comment]
Great! I plan to release a new version of SeisNoise once in the next few days, after we ship the new SeisIO release.

**Comment by dylanmikesell** [comment]
Okay. We will make sure to update both packages before we continue with the
AWS tools.

Dylan
