### ISSUE TITLE
b should be normalized to link robust stacking weights to correlation-coefficient

### ISSUE THREAD

**Issue by jaredbryan881** [tclements/SeisNoise.jl#8]
Bold should be normalized such that ||**b**||=1 for the weight computation, as per Pavlis and Vernon (2010). 
Here in L80 & L83 (and again when this is iterated) `Bold` becomes `Bold ./ norm(Bold,2)`:
https://github.com/tclements/SeisNoise.jl/blob/86cdb8e7cfa47dbd8cbef9833d5ca1a613ef595f/src/stacking.jl#L80-L86
Removing L86 (and the normalization of w in later iterations) then gives the weights a real meaning, namely `w.*r = cor(Bold, A[ii])`. This explains the similarity (and gives the proportionality) in Chengxin's slide 32.

Also, P&V2010 compute the L1 norm in the numerator for convergence checks:
https://github.com/tclements/SeisNoise.jl/blob/86cdb8e7cfa47dbd8cbef9833d5ca1a613ef595f/src/stacking.jl#L91
The choice of convergence criteria is nonunique, so L2 in the numerator probably works just as well, albeit with modified eps.

**Comment by tclements** [comment]
Thanks, I'll look into this this afternoon.

**Comment by tclements** [comment]
I fixed the robust stack with your suggestions. Feel to submit a PR in the future if you see any easy fixes or have any new features.
