### ISSUE TITLE
io.jl

### ISSUE THREAD

**Issue by dylanmikesell** [tclements/SeisNoise.jl#80]
Hi Tim,
What do you think about returning the filename in save_corr(). That would not change anything other than give the user the filename. We would like that for the AWS tools we are building.  Please let us know if you're open to that.
Thanks.

**Comment by tclements** [comment]
Hey Dylan, 

This would be a pretty easy change. I'll try to get this done tomorrow - I have a bunch of (hopefully) improvements I've been putting off from adding to the module.

**Comment by mcardenass** [comment]
Hi Tim
 In the new 0.5.2 SeisNoise version, save_corr() function send the error:

julia> save_corr(C,"JLD2s")
ERROR: type DataType has no field mutable ....

The structure of my cross-correlation data is

julia> C
CorrData with 1 Corrs
      NAME: "LI.ST01..01.LI.ST02..02"          
        ID: "2014-09-29"                       
       LOC: 19.4226 N, -99.1787 E, 0.0 m
      COMP: "12"                               
   ROTATED: false                              
 CORR_TYPE: "PCC"                              
        FS: 125.0
      GAIN: 1.0
   FREQMIN: 4.0
   FREQMAX: 48.0
    CC_LEN: 180.0
   CC_STEP: 30.0
  WHITENED: true                               
 TIME_NORM: ""                                 
      RESP: a0 1.0, f0 1.0, 0z, 0p
      MISC: 0 entries                          
     NOTES: 7 entries                          
      DIST: 0.00336239
       AZI: 151.536
       BAZ: 331.536
    MAXLAG: 8.0
         T: 2014-09-29T12:00:00                …
      CORR: 2001×1 Matrix{Float32}             

Thanks for yours comments

**Comment by tclements** [comment]
This is likely related to how JLD2 (https://github.com/JuliaIO/JLD2.jl/issues/320, https://github.com/JuliaIO/JLD2.jl/issues/337, https://github.com/JuliaIO/JLD2.jl/issues/365) interacts with newer versions of Julia. I need to bump the compat of JLD2 to the newest versions - will do that right now.

**Comment by mcardenass** [comment]
Thanks Tim
I just tried an older version of Julia (v1.6), JLD2 works. Please let me know if only updating SeisNoise solves the problem. Greeting

**Comment by tclements** [comment]
I updated SeisNoise to use the latest versions of JLD2. You should try updating SeisNoise - let me know if you're still having problems with JLD2 after updating, thanks!

**Comment by mcardenass** [comment]
yes, the problem persist with SeismicNoise V 0.5.3 running Julia 1.7

(@v1.7) pkg> update SeisNoise
    Updating registry at `~/.julia/registries/General.toml`
  No Changes to `~/.julia/environments/v1.7/Project.toml`
  No Changes to `~/.julia/environments/v1.7/Manifest.toml`

(@v1.7) pkg> status
      Status `~/.julia/environments/v1.7/Project.toml`
  [6e4b80f9] BenchmarkTools v1.2.2
  [052768ef] CUDA v3.7.0
  [5789e2e9] FileIO v1.12.0
  [033835bb] JLD2 v0.2.4
  [91a5bcdd] Plots v1.25.6
  [03de775e] SAC v0.3.2 `https://github.com/anowacki/SAC.jl#master`
  [2da01664] SeisConvert v0.1.0 `https://github.com/xtyangpsp/SeisConvert.jl#master`
  [7496752f] SeisDvv v0.1.0 `https://github.com/tclements/SeisDvv.jl#master`
  [b372bb87] SeisIO v1.2.1
  [8cc7c3c0] SeisNoise v0.5.3


ERROR: LoadError: type DataType has no field mutable
Stacktrace:

**Comment by tclements** [comment]
Looks like you have JLD2 v0.2.4 installed (an older version) - could you try removing and adding the newest version of JLD2: 

```julia
pkg>rm JLD2
pkg> add JLD2
```
You might have another package that is preventing the newest version of JLD2 from being installed.

**Comment by mcardenass** [comment]
It's working, thanks !!

**Comment by tclements** [comment]
Great! closing this issue.
