### ISSUE TITLE
Error: rfft not defined

### ISSUE THREAD

**Issue by OUCyf** [tclements/SeisNoise.jl#95]
Hi Tim!
It's the first time that I use Julia, and I get an error after installing "SeisNoise" successfully on my MacBook as follow:

![Xnip2021-09-23_00-38-58](https://user-images.githubusercontent.com/25765271/134385549-444546a3-61df-4c2a-8bd2-af6afdac4381.jpg)

It doesn't seem to have found the 'rfft' function. Do you konw the reason?

Thanks in advance

Fu

**Comment by tclements** [comment]
Hello! Can you let me know which version of Julia and SeisNoise you are using? `rfft` should be exported through FFTW.jl and SeisNoise.jl.

**Comment by OUCyf** [comment]
yep, thanks~ Julia version v1.6.2 and SeisNoise is the latest version. And I test the following functions included in script 
 'compute_fft.jl': process_fft, rfft, remove_amp!, remove_amp; all of these does not work. And I use Pkg.test("SeisNoise"), it works!

Maybe because I'm not familiar with Julia...

**Comment by tclements** [comment]
I can reproduce this on Julia v1.6.2. An older version of SeisNoise (3.1) is being installed that does not have `rfft`. I need to update CUDA.jl to the newest version, which requires v1.6+. I'll make that change and tag a new version. In the meantime you can use the development version by doing 

`julia
(@v1.6) pkg> add SeisNoise#master
`

which I just checked works on v1.6.2.

**Comment by OUCyf** [comment]
Good to know. Thanks~

**Comment by tclements** [comment]
This should be fixed with commit 0eba10ca056ddbc73da50a137b4d2c13cea956ef. You should be able to remove SeisNoise v0.3.1 and add the new v0.5.2.
