### ISSUE TITLE
SeisNoise.correlate corr_type arguments

### ISSUE THREAD

**Issue by mcardenass** [tclements/SeisNoise.jl#97]
Hello Timothy, 

I'm trying to use arguments in corr_type's correlate function. I am particularly interested in using coherence and PCC. However, these do not work. For example:
C = correlate (FFT [jj], FFT [kk],maxlag, corr_type= "PCC")

I am also interested in using the phase-weighted stack in the next sentence:
      stack!(C, allstack = true)
How include the argument?

Thanks for the feedback

**Comment by tclements** [comment]
Hello - thanks for pointing this out! Apologies, I believe the documentation is a little unclear here -  if you want to use the `PCC`, you need to use the `phase` function to create `FFTData` from `RawData`. Here is a MWE for using `phase`: 

```julia 
using SeisNoise, SeisIO
fs = 40. # sampling frequency in Hz
freqmin,freqmax = 0.1,0.2 # min and max frequencies
cc_step, cc_len = 450, 1800 # corrleation step and length in S
maxlag = 60. # maximum lag time in correlation
s = "2019-02-03"
t = "2019-02-04"
S1 = get_data("FDSN","CI.SDD..BHZ",src="SCEDC",s=s,t=t)
S2 = get_data("FDSN","CI.PER..BHZ",src="SCEDC",s=s,t=t)
R = RawData.([S1,S2],cc_len,cc_step)
FFT = phase.(R) # use phase function to get analytic representation 
C = correlate(FFT[1],FFT[2],maxlag, corr_type="PCC") 
```

I need to make a fix for the `phase` function, will get that out shortly. I can also have the `correlate` function automatically check if we should use the `ifft` or `irfft` in the correlate function based on the size of the input `FFTData`. 

For the `stack` and `stack!` functions you would do: 

```julia
stack!(C, allstack=true, stacktype=pws)
```

or you could just use the `pws` function: 
```julia
pws(C, pow)
```

which will do the same thing. 

Looks like I need to fix the docstring in `stack!`. to correctly use `stacktype`.

**Comment by mcardenass** [comment]
Thanks Timothy, functions are working
